-- ============================================================
-- 01_create_schemas.sql
-- Create DB schemas
-- Run in Snowflake
-- ============================================================

-- Database
CREATE DATABASE IF NOT EXISTS HEALTHCARE;

-- Schemas
CREATE SCHEMA IF NOT EXISTS HEALTHCARE.RAW;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE.SNAPSHOTS;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE.PROD;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE.TEST_FAILURES;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE.OPS;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE   = 'X-SMALL'
    AUTO_SUSPEND     = 120
    AUTO_RESUME      = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- ── Roles ────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS TRANSFORM;
CREATE ROLE IF NOT EXISTS REPORTER;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER;

-- Grant database usage
GRANT USAGE ON DATABASE HEALTHCARE TO ROLE TRANSFORM;
GRANT USAGE ON DATABASE HEALTHCARE TO ROLE REPORTER;

-- Allow TRANSFORM to create new schemas (needed for dbt to create target schemas)
GRANT CREATE SCHEMA ON DATABASE HEALTHCARE TO ROLE TRANSFORM;

-- TRANSFORM role — full access to all schemas
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE.RAW          TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE.SNAPSHOTS    TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE.PROD         TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE.TEST_FAILURES TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON SCHEMA HEALTHCARE.OPS          TO ROLE TRANSFORM;

-- REPORTER role — read only on PROD
GRANT USAGE  ON SCHEMA HEALTHCARE.PROD                 TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE.PROD   TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE.PROD TO ROLE REPORTER;

-- Future grants for TRANSFORM
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE.RAW          TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE.SNAPSHOTS    TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE.PROD         TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE.TEST_FAILURES TO ROLE TRANSFORM;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HEALTHCARE.OPS          TO ROLE TRANSFORM;

-- ── Service account user ─────────────────────────────────────
-- Replace RSA_PUBLIC_KEY with your actual public key content
CREATE USER IF NOT EXISTS dbt
    DEFAULT_ROLE      = TRANSFORM
    DEFAULT_WAREHOUSE = COMPUTE_WH
    COMMENT           = 'dbt service account — key-pair auth only';

-- ALTER USER dbt SET RSA_PUBLIC_KEY='<KEY_HERE>';  -- run after generating keys

GRANT ROLE TRANSFORM TO USER dbt;
